theme: jekyll-theme-cayman
title: MQLess
description: Actor model framework on top of AWS Lambda
show_downloads: false
github:
  is_project_page: true
  repository_name: MQLess
  repository_url: https://github.com/somdoron/mqless
  owner_url: https://github.com/somdoron
  owner_name: Doron Somech
